name: manual_trigger
on:
  workflow_dispatch:
jobs:
  katalon-testops:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
        version: '8.1.0'
        projectPath: '${{ github.workspace }}'
        args: '-noSplash -runMode=console -retry=0 -testSuitePath="Test Suites/Example Testsuite" -browserType="Chrome (headless)" -executionProfile="default" -apiKey=${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'
